@extends('Layout')
@section('title','Negocios')
@section('header','Negocios')
@section('hd-table')
    <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Telefono</th>
        <th>Correo</th>
        <th>Ubicacion</th>
        <th>Encargados</th>
    </tr>
@endsection